gems: [jekyll-seo-tag]
name: Rémi Huguet
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
logo: "/assets/img/remi-nb.jpg"
title: Rémi Huguet
description: Software developper, entrepreneur, PhD
url: remihuguet.com
author:
    twitter: RemiHuguet
twitter:
    username: RemiHuguet
